# frontend/.streamlit/secrets.toml

# API Configuration
API_BASE_URL = "http://localhost:8000/api"

# Optional: Add other configuration
[app]
debug = true
auto_refresh_interval = 30

[auth]
jwt_expire_minutes = 30

[portfolio]
default_currency = "INR"
default_allocation = 5.0